### ISSUE TITLE
Client Example

### ISSUE THREAD

**Issue by oxr463** [creachadair/jrpc2#101]
Maybe I missed it, but could you please include an example of the client?

**Comment by creachadair** [comment]
Apologies, I did not see this issue until just now for some reason. There are some examples of how to use the client in the package docs: https://pkg.go.dev/github.com/creachadair/jrpc2#pkg-examples

Are those what you were looking for, or did you have something else in mind?

**Comment by creachadair** [comment]
I'm going to close this given the examples linked above, but feel free to reopen it with more specifics if there are cases you are interested in not covered there.
