### ISSUE TITLE
Allow "Content-Type: application/json; charset=utf-8"

### ISSUE THREAD

**Issue by aditya1702** [creachadair/jrpc2#110]
Currently it looks like only "application/json" is allowed by jrpc2's handler - https://github.com/creachadair/jrpc2/blob/main/jhttp/bridge.go#L60

We would like to allow "application/json; charset=utf-8" too since some of our partners use that request type.

**Comment by creachadair** [comment]
This is merged and tagged at or after v1.1.2.
