### ISSUE TITLE
Feature Request: Custom Error Handling Middleware

### ISSUE THREAD

**Issue by 0xivanov** [creachadair/jrpc2#115]
**Title:** Feature Request: Custom Error Handling Middleware

**Context:**

I've been using `jrpc2` library for handling JSON-RPC communications in my Go project, and I find it extremely useful and easy to work with. However, I've come across a scenario where I need to implement custom error handling middleware for the JSON-RPC server, but I couldn't find a built-in method to achieve this.

In my project, I need to centralize error handling logic for my JSON-RPC methods, which includes logging errors, transforming them into appropriate JSON-RPC error responses, and possibly performing additional actions based on the error type. As `jrpc2` currently lacks built-in support for custom error handling middleware, I've had to implement this logic separately for each method, resulting in code duplication and reduced maintainability.

**Feature Request:**

I would like to request the addition of a feature to `jrpc2` that allows users to define custom error handling middleware for the JSON-RPC server. This would involve the ability to register a global error handler function or middleware that intercepts errors occurring during method execution and handles them centrally.

**Proposed Solution:**

One possible solution could be to introduce an `ErrorMiddleware` interface similar to the `jrpc2.Handler` interface, which defines a method for handling errors:

```go
type ErrorMiddleware interface {
    HandleError(error) interface{}
}
```

Users could then implement this interface to define custom error handling logic, and register their middleware with the JSON-RPC server. When an error occurs during method execution, the server would invoke the error middleware to handle the error and generate an appropriate error response.

**Example Usage:**

```go
// Custom error middleware implementation
type CustomErrorHandler struct{}

func (h *CustomErrorHandler) HandleError(err error) interface{} {
    // Custom error handling logic
    log.Println("Error:", err)
    return jrpc2.ErrorInternal("Internal server error")
}

// Register custom error middleware with the server
server.RegisterErrorMiddleware(&CustomErrorHandler{})
```

**Benefits:**

- Centralized error handling logic: Allows users to centralize error handling logic for JSON-RPC methods, reducing code duplication and improving maintainability.
- Customizable error responses: Provides flexibility to customize error responses based on application requirements.
- Enhanced debugging: Facilitates easier debugging and troubleshooting by logging errors and providing meaningful error messages to clients.

**Comment by creachadair** [comment]
Hi @0xivanov. I may be missing some aspect of your request, but is there some reason the server would need to handle this directly? It doesn't seem to require any access to the server's internal plumbing.

I believe you could get the same effect by packaging the middleware as a separate library. From the example it's not clear what the return value from the handler is meant to be, but perhaps something like:

```go
package middle

// ErrorHandler is a function that handles errors reported by a method handler.
type ErrorHandler func(context.Context, *jrpc2.Request, error) error

func HandleErrors(eh ErrorHandler, h jrpc2.Handler) jrpc2.Handler {
   return func(ctx context.Context, req *jrpc2.Request) (any, error) {
      res, err := h(ctx, req)
      if err != nil {
         return nil, eh(ctx, req, err)
      }
      return res, nil
   }
}
```

Then at registration, something like:

```go
m := handler.Map{"Foo": middle.HandleErrors(fixup, handler.New(doAThing)}
```

And of course, you could further hide this if you like by providing a function to do both of these in a single step, e.g.,

```go
package middle

func WrapHandler(onErr func(context.Context, *jrpc2.Request, error) error) func(any) jrpc2.Handler {
   return func(f any) jrpc2.Handler {
      return middle.HandleError(onErr, handler.New(f))     
   }
}
```

and then the caller can wire up whatever they want:

```go
package srv

func fixErrors(ctx context.Context, req *jrpc2.Request, err error) error {
   // ... whatever this does
}

var middleHandler = middle.WrapErrors(fixErrors)

// ...
m := handler.Map{
   "Foo":  middleHandler(foo),
   "Bar":  middleHandler(bar),
   // etc. 
}
```

This would allow the caller to replace existing uses of `handler.New` directly. All of that could be done in a separate package without having to modify the server plumbing at all.

**Comment by 0xivanov** [comment]
Hi @creachadair ,

Thanks a lot for your quick response and for suggesting a solution. I tried out your idea, and it worked like a charm! Using a separate middleware library for error handling makes total sense and keeps things clean.

Your help really saved me some time and headache. I'll definitely keep exploring jrpc2 as I'm still new to go and the json-rpc specification.

Thanks again for your support!

Cheers.
