### ISSUE TITLE
Support server -> client requests

### ISSUE THREAD

**Issue by radeksimko** [creachadair/jrpc2#18]
Currently the library supports just server to client notifications via [`jrpc2.ServerPush()`](https://pkg.go.dev/github.com/creachadair/jrpc2?tab=doc#ServerPush).

[The Language Server Protocol spec](https://microsoft.github.io/language-server-protocol/specifications/specification-current/) describes a number of RPC calls which are meant to be sent from the server to the client and responded to - i.e. treated as requests, rather than notifications.

For example:

 - `client/registerCapability`
 - `client/unregisterCapability`
 - `window/showMessageRequest`
 - `window/workDoneProgress/create`
 - `workspace/applyEdit`
 - `workspace/configuration`
 - `workspace/workspaceFolders`

and here are some examples of how it's used:

 - [gopls](https://github.com/golang/tools/blob/99be2d6e796f9bc16b66c42a44c468872fd31f66/internal/lsp/protocol/tsclient.go#L70-L117) (server)
 - [Sublime Text LSP](https://github.com/sublimelsp/LSP/blob/33569cde267ff754cb39467083102aeb94ce65a2/plugin/core/windows.py#L529-L551) (client)

Would there be any interest in adding support for this functionality to the library?

**Comment by creachadair** [comment]
It's an interesting request. It's not valid JSON-RPC 2, but LSP is a pretty important user of the protocol so it's worth thinking about ways to support the style of abuse. I'll fiddle with it and see if I can come up with something that doesn't mangle the API too badly.

**Comment by creachadair** [comment]
@radeksimko I made an attempt at implementing this in #25. I'd be interested in any feedback you might have.
