### ISSUE TITLE
Some server need to receive message with "\n" ending

### ISSUE THREAD

**Issue by bigplum** [creachadair/jrpc2#35]
I am a newcomer for Golang. I've no idea to find a better way to resolve it, just add the char after encoding json string.

`
	c.log("Outgoing batch: %s", string(b))

	b = append(b, []byte{0x0a}...) // adding 0x0a to notify server ending this request

	if err := c.ch.Send(b); err != nil {
		return nil, err
	}
`

**Comment by creachadair** [comment]
Hi, could you add some more detail about what you're trying to do? It looks like the issue title is truncated, and I'm not sure what you're asking.

From what you wrote above, it sounds like maybe you need to delimit messages by newlines. If that's right, the framing of messages is handled by the `channel` package. The [adder example](https://github.com/creachadair/jrpc2/blob/master/cmd/examples/adder/adder.go) demonstrates how to set up line framing on a channel, for instance.

**Comment by bigplum** [comment]
Sorry for forgetting modify the title.

I'am writing a rpc client to send message to server. When I compare the tcp packets sent by jrpc2 and net/rpc, I find there is a difference between them. It was the message ending, net/rpc sent the message with "\n" but jrpc2 not.

So I modify the code and send message and receive the reply.

**Comment by creachadair** [comment]
The way `jrpc2` sends a message depends on what channel framing you use. The server doesn't control the message framing: If you want messages to be sent with a trailing newline as you describe, you'll probably want to use the [`channel.Line`](http://godoc.org/github.com/creachadair/jrpc2/channel#Line) framing function when you set up the channel. In any case, it isn't necessary to modify the server itself.

**Comment by creachadair** [comment]
I don't think there's any functional change required here. However, if you have any suggestions for how I could improve the documentation, sample code, etc., to make this aspect of the library easier to understand, I welcome them.

**Comment by creachadair** [comment]
Since this issue doesn't seem to require any action, I'm going to close it—but if you have specific requests for better documentation, or further questions, please feel free to re-open it.
