### ISSUE TITLE
`PushCall` fails due to `duplicate request id`

### ISSUE THREAD

**Issue by Lachann** [creachadair/jrpc2#36]
The `jrpc2.PushCall` results in `[-32600] duplicate request id "1"` error being returned to the client side after sending reply from the callback. It seems to be coming from `checkAndAssign` function on the server side.

Attached (simplified and contrived) client-server setup to reproduce the error. 
[client-server.zip](https://github.com/creachadair/jrpc2/files/5919540/client-server.zip)

At first glance, it seems to happen because the check for duplicate ID in `checkAndAssign` function happens before the `PushCall` response it recognized as such and handled:
https://github.com/creachadair/jrpc2/blob/default/server.go#L273-L274
https://github.com/creachadair/jrpc2/blob/default/server.go#L277-L282

I've made a quick fix by moving that section before the duplicate request check and it seems to fix the problem, but I don't know what other impact it might have:
https://github.com/Lachann/jrpc2/commit/3ffe8ef8ad9d7350e94eddf4fb7a67e3cbd153a7

**Comment by creachadair** [comment]
Thank you for the detailed report and reproduction case, and apologies for the error. I think your diagnosis is essentially correct. I'll get a fix out soon.

**Comment by creachadair** [comment]
Can you please check whether #37 addresses the problem for you?

**Comment by Lachann** [comment]
Yup, works now. Thanks!

**Comment by creachadair** [comment]
The fix is now visible at or after v0.11.2.
