### ISSUE TITLE
Push notifications/requests from outside handlers

### ISSUE THREAD

**Issue by radeksimko** [creachadair/jrpc2#38]
In [our language server](https://github.com/hashicorp/terraform-ls) we spin up a few routines as part of compatible `server.Service`

https://github.com/creachadair/jrpc2/blob/446228c04965bd4328cac6e1a43af81198ddf998/server/loop.go#L13-L20

These routines can be long-lived, but never longer than the lifetime of a session - hence we spin them up as part of `Assigner` and stop as part of `Finish`.

In particular we have three things running outside of handlers currently:

 - watcher (watching the filesystem for relevant changes)
 - walker (walking the filesystem on `initalize` to understand relationships between different folders user has in the hierarchy)
 - "module loader" - this is basically a task queue with a worker pool which executes various tasks on the background without blocking any handler response, reflecting that these tasks may take a while to finish and there can be many queued
    - config parsing
    - obtaining version of Terraform
    - parsing metadata relevant to open files/folders

This all works aok, but we'd also like to report progress on some of these operations, i.e. send `$/progress` notifications back to the client.

I think the best way of solving that might be introduction of a new function which can extract the `*Server` out of the context as part of a handler. This then allows for it to be persisted somewhere outside of the short-lived handler context.

```go
func ServerFromContext(ctx context.Context) (*Server, bool) {
  s, ok := ctx.Value(serverKey{}).(*Server)
  return s, ok
}
```
alternatively instead of exposing the whole `*Server` the function could extract an interface such as this one
```go
type ServerPusher interface {
  Callback(ctx context.Context, method string, params interface{}) (*Response, error)
  Notify(ctx context.Context, method string, params interface{}) error
}
```
just to discourage from using other parts of the API in that context. Obviously the interface can easily be just casted back to `*Server`, but it would still communicate the intentions better?

--- 

I would be happy to send a PR - let me know what you think.

**Comment by creachadair** [comment]
Since the ability to notify requires the client connection, could the maintenance goroutines simply capture a closure? For example:

```go
notify := func(arg interface{}) error {
   return jrpc2.PushNotify(ctx, "$/progress", arg)
}
go maintain(notify)
```

or words to that effect? Not that what you're describing wouldn't work either, but I'm not yet convinced we need a new mechanism for this case.

**Comment by radeksimko** [comment]
I wouldn't mind capturing a closer, but by the time the goroutine gets to execute the closure, the context will likely be cancelled already, which would be fine for extracting the server instance, but not for the actual requests, because these also inherit the same context.

https://github.com/creachadair/jrpc2/blob/e9f1949a36d2076b54041edc5cca1f62bc865778/ctx.go#L44

https://github.com/creachadair/jrpc2/blob/e9f1949a36d2076b54041edc5cca1f62bc865778/ctx.go#L59

**Comment by creachadair** [comment]
I see, yes—your point about the lifetime of the context makes a closure less attractive. (It would work fine with the current implementation, but I wouldn't want to commit to that)

Given that the API of server is intentionally small, I think it would be OK to expose it to the handler. The only "bad" thing a handler could do is to call `Wait` or `WaitStatus`, which would deadlock because the server will block on the handler returning. But I think we can just document that.

**Comment by creachadair** [comment]
Can you please try #39 to see if it addresses your needs?

**Comment by creachadair** [comment]
The change from #39 is visible at and after tag v0.12.0.
