### ISSUE TITLE
Checksum mismatch for `v0.23.0`

### ISSUE THREAD

**Issue by radeksimko** [creachadair/jrpc2#53]
The checksum obtained/cached by the public module proxy seems to mismatch with the package version published as `v0.23.0`. Can you confirm this was merely an accident such as a force push of a tag?

To reproduce:

```
go clean -modcache
go get github.com/creachadair/jrpc2@v0.23.0
go clean -modcache
go mod download -x
```
```
...
# get https://proxy.golang.org/github.com/creachadair/jrpc2/@v/v0.23.0.mod: 200 OK (0.010s)
verifying github.com/creachadair/jrpc2@v0.23.0/go.mod: checksum mismatch
	downloaded: h1:sQpAMSxj70eK02yAVq48uEabs2AXkJDkcBSS4bxfq5M=
	go.sum:     h1:zkMpdS1/qjsat0KP72Do9nL2nnVTVKvnULo55RwOuG0=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
```

It appears that the only difference is go version between the two:

https://github.com/creachadair/jrpc2/blob/v0.23.0/go.mod#L9
https://proxy.golang.org/github.com/creachadair/jrpc2/@v/v0.23.0.mod

**Comment by creachadair** [comment]
Hmm, I didn't do this intentionally, but it's possible I ham-handed the push. I will take a look after my meetings, and sorry for the trouble.

**Comment by creachadair** [comment]
So, based on the reflog it appears I did wrong here: I added the retractions for the buggy module versions, and then realized that the retraction declaration would not work with older Go versions and updated the toolchain version marker. I thought that I had not yet pushed the tag up to GitHub at the time I made that change, but apparently I did (that part doesn't show in the reflog, but the fact that your'e getting this checksum error strongly implies it).

If you are able to bump to 0.24.1 that is probably the easiest fix. I don't think your modules were using any of the code I changed in the 0.24 tag. If that does not work, I'd be happy to tag a patch on v0.23 to retract the one I broke. Let me know what you would prefer.

**Comment by radeksimko** [comment]
That is fine, we have already bumped to 0.24.1 today. I was merely raising this issue to understand what happened, make sure it wasn't caused by any rogue activity by anyone and let you know - just in case you weren't aware.

So your answer here is sufficient for me to close this and consider it done. 👍🏻 

Thank you.

**Comment by creachadair** [comment]
Thank you for reporting it. It was definitely accident rather than malice. 🙂  I think I will add a retraction for that tag just to avoid anyone else running afoul of it.
